/*
 * Edge Sentinel — Cellular Threat Detection for Android
 * Copyright (C) 2024-2026 BP22 Intel. All Rights Reserved.
 *
 * This software is proprietary and confidential. Unauthorized copying,
 * modification, distribution, or use of this software, in whole or in
 * part, is strictly prohibited without prior written permission from
 * BP22 Intel.
 */

package com.bp22intel.edgesentinel.export

import android.content.Context
import android.content.Intent
import android.os.Build
import androidx.core.content.FileProvider
import com.bp22intel.edgesentinel.analysis.SituationBrief
import com.bp22intel.edgesentinel.domain.model.Alert
import dagger.hilt.android.qualifiers.ApplicationContext
import org.json.JSONObject
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Exports alert data as plain-text reports and CSV files for sharing
 * via Android's ShareSheet.
 */
@Singleton
class AlertExporter @Inject constructor(
    @ApplicationContext private val context: Context
) {

    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm z", Locale.US).apply {
        timeZone = TimeZone.getDefault()
    }

    private val csvDateFormat = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.US).apply {
        timeZone = TimeZone.getDefault()
    }

    /**
     * Generate a plain-text threat report suitable for clipboard/messaging.
     */
    fun generateTextReport(
        alerts: List<Alert>,
        situationBrief: SituationBrief?,
        latitude: Double? = null,
        longitude: Double? = null
    ): String = buildString {
        appendLine("EDGE SENTINEL THREAT REPORT")
        appendLine("Generated: ${dateFormat.format(Date())}")
        appendLine("Device: ${Build.MANUFACTURER} ${Build.MODEL}")
        if (latitude != null && longitude != null) {
            appendLine("Location: $latitude, $longitude")
        }
        appendLine()

        if (situationBrief != null) {
            appendLine("SITUATION SUMMARY:")
            appendLine(situationBrief.summary)
            appendLine()
        }

        appendLine("ACTIVE ALERTS (${alerts.size}):")
        alerts.forEachIndexed { index, alert ->
            val details = alert.detailsJson.parseJsonSafe()
            val cellId = details.optInt("cellId", -1).let { if (it == -1) "N/A" else it.toString() }
            val signal = details.optInt("signalStrength", Int.MIN_VALUE).let {
                if (it == Int.MIN_VALUE) "N/A" else "${it}dBm"
            }
            appendLine("${index + 1}. [${alert.threatType.name}] ${alert.severity.name} — CID: $cellId, Signal: $signal")
            appendLine("   ${alert.summary}")
        }

        if (situationBrief != null && situationBrief.recommendations.isNotEmpty()) {
            appendLine()
            appendLine("RECOMMENDATIONS:")
            situationBrief.recommendations.forEach { rec ->
                appendLine("- $rec")
            }
        }

        appendLine()
        appendLine("---")
        appendLine("Report generated by Edge Sentinel")
        appendLine("Copyright (C) 2024-2026 BP22 Intel. All Rights Reserved.")
    }

    /**
     * Generate a CSV export of the alert history.
     */
    fun generateCsv(alerts: List<Alert>): String = buildString {
        appendLine("alertId,timestamp,type,severity,confidence,summary,cellId,lac,mcc,mnc,signal")
        alerts.forEach { alert ->
            val details = alert.detailsJson.parseJsonSafe()
            val cellId = details.optString("cellId", "")
            val lac = details.optString("lac", "")
            val mcc = details.optString("mcc", "")
            val mnc = details.optString("mnc", "")
            val signal = details.optString("signalStrength", "")
            val timestamp = csvDateFormat.format(Date(alert.timestamp))
            val escapedSummary = alert.summary.csvEscape()

            appendLine("${alert.id},$timestamp,${alert.threatType.name},${alert.severity.name},${alert.confidence.name},$escapedSummary,$cellId,$lac,$mcc,$mnc,$signal")
        }
    }

    /**
     * Share a plain-text report via Android ShareSheet.
     */
    fun shareTextReport(
        alerts: List<Alert>,
        situationBrief: SituationBrief?,
        latitude: Double? = null,
        longitude: Double? = null
    ): Intent {
        val report = generateTextReport(alerts, situationBrief, latitude, longitude)
        return Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Edge Sentinel Threat Report")
            putExtra(Intent.EXTRA_TEXT, report)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
    }

    /**
     * Share a CSV export via Android ShareSheet using a temporary file.
     */
    fun shareCsvExport(alerts: List<Alert>): Intent {
        val csv = generateCsv(alerts)
        val fileName = "edge_sentinel_alerts_${SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())}.csv"
        val cacheDir = File(context.cacheDir, "exports").apply { mkdirs() }
        val csvFile = File(cacheDir, fileName).apply { writeText(csv) }

        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            csvFile
        )

        return Intent(Intent.ACTION_SEND).apply {
            type = "text/csv"
            putExtra(Intent.EXTRA_SUBJECT, "Edge Sentinel Alert Export")
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }
    }

    private fun String.parseJsonSafe(): JSONObject {
        return try {
            JSONObject(this)
        } catch (_: Exception) {
            JSONObject()
        }
    }

    private fun String.csvEscape(): String {
        return if (contains(',') || contains('"') || contains('\n')) {
            "\"${replace("\"", "\"\"")}\""
        } else {
            this
        }
    }
}
